---
title: "Privacy policy / About"
lang: en
---

# Who we are

Pronoun ‘we’ is, for now, actually just me, Klaas Jan Runia, BSc (Honours) Mathematics and Physics MInstP AMIMA, and a student for the Master of Physics (MPhys) at The Open University in Walton Hall, Milton Keynes, UK. I am a Member of the Institute of Physics (IOP) and an Associate Member of the Institute of Mathematics and its Applications (IMA), both established in the United Kingdom.

# What personal data I collect

The short answer: I don’t. The longer answer: I don’t store personal data nor do I transfer any personal data. The longest answer: I don’t store personal data nor do I transfer any personal data because I absolutely don’t want all that.

# Embedded content from other websites

Articles on this site may include embedded content (e.g. YouTube videos, Twitter tweets, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.

These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content. I have and desire zero access to all of that.