---
title: "Privacybeleid / Over ons"
lang: nl
---

# Wie we zijn

Het voornaamwoord ‘we’ is voorlopig eigenlijk gewoon mijzelf, Klaas Jan Runia, BSc (Honours) Mathematics and Physics MInstP AMIMA, en een student voor de Master of Physics (MPhys), aan The Open University in Walton Hall, Milton Keynes in het Verenigd Koninkrijk. Ik ben een Member van het Institute of Physics (IOP) en een Associate Member van het Institute of Mathematics and its Applications (IMA), beiden gevestigd in het Verenigd Koninkrijk.

# Welke persoonlijke gegevens bewaar ik

Het korte antwoord: dat doe ik niet. Het langere antwoord: ik bewaar geen persoonlijke data en ik stuur ook geen persoonlijke data door. Het langste antwoord: ik bewaar geen persoonlijke data en ik stuur ook geen persoonlijke data door omdat ik dat allemaal absoluut niet wil.

# Ingebedde inhoud van andere websites

Artikelen op deze website zouden ‘embedded content’ kunnen bevatten (video’s van YouTube, tweets van Twitter). Deze ‘embedded content’ van deze websites gedragen zich op dezelfde manier als wanneer de bezoeker die websites heeft bezocht.

Deze websites kunnen data van je verzamelen, cookies gebruiken, additionele derdepartijtracking en je interactie met de video of tweet etc. opslaan. Ik heb en wil nul toegang tot dat alles.